export const ADD_PRODUCT ='ADD_PRODUCT';
export const SUCCESSFULL_ADD_PRODUCT = 'SUCCESSFULL_ADD_PRODUCT';
export const FAILED_ADD_PRODUCT = 'FAILED_ADD_PRODUCT'; 

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const SUCCESSFULL_PRODUCTS_DOWNLOAD = 'SUCCESSFULL_PRODUCTS_DOWNLOAD';
export const FAILED_PRODUCTS_DOWNLOAD = 'FAILED_PRODUCTS_DOWNLOAD';

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const SUCCESSFULL_DELETE_PRODUCT = 'SUCCESSFULL_DELETE_PRODUCT';
export const FAILED_DELETE_PRODUCT = 'FAILED_DELETE_PRODUCT';

export const GET_UPDATE_PRODUCT = 'GET_UPDATE_PRODUCT';
export const START_UPDATE_PRODUCT = 'START_UPDATE_PRODUCT'; 
export const SUCCESSFULL_UPDATE_PRODUCT = 'SUCCESSFULL_UPDATE_PRODUCT';
export const FAILED_UPDATE_PRODUCT = 'FAILED_UPDATE_PRODUCT';

export const SHOW_ALERT = 'SHOW_ALERT'; 
export const HIDE_ALERT = 'HIDE_ALERT'; 