export const ADD_PRODUCT ='ADD_PRODUCT';
export const SUCCESSFULL_ADD_PRODUCT = 'SUCCESSFULL_ADD_PRODUCT';
export const FAILED_ADD_PRODUCT = 'FAILED_ADD_PRODUCT'; 

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const SUCCESSFULL_PRODUCTS_DOWNLOAD = 'SUCCESSFULL_PRODUCTS_DOWNLOAD';
export const FAILED_PRODUCTS_DOWNLOAD = 'FAILED_PRODUCTS_DOWNLOAD';
